### ISSUE TITLE
Dataset initialization problems

### ISSUE THREAD

**Issue by fosfrancesco** [HuwCheston/Jazz-Trio-Database#1]
Hello, thank you for sharing this work!
I see the default corpus in `src/clean/make_dataset.py` is `corpus_chronology`. 
But this corpus doesn't have the `in_30_corpus` column. Should we use `corpus_updated` instead?

**Comment by pmcharrison** [comment]
Hi @fosfrancesco, Huw is on holiday right now but he should be able to get back to you soon after he gets back! Glad you are interested in the dataset.

**Comment by HuwCheston** [comment]
Thanks Francesco, this change should definitely be made for anyone hoping to build the database from source in the future :) To make things easier (given that YouTube links are liable to be taken down), I've now made the audio available by request [on this Zenodo record](https://zenodo.org/records/13828030). Hope you've been able to make use of this!

**Comment by fosfrancesco** [comment]
I was able to download the data and use the corresponding annotations. So all good from my side! Thank you for this work
